set_property -dict [list \
	CONFIG_VOLTAGE {3.3} \
	CFGBVS {VCCO} \
	BITSTREAM.GENERAL.COMPRESS {TRUE} \
	BITSTREAM.CONFIG.CONFIGRATE {33}  \
	BITSTREAM.CONFIG.SPI_BUSWIDTH {4} \
	BITSTREAM.CONFIG.SPI_32BIT_ADDR {NO} \
	BITSTREAM.CONFIG.SPI_FALL_EDGE {YES} \
	] [current_design]
